# Generated by Django 4.2.5 on 2023-10-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_contact_message_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
